import type {
  AgentRunPersonas,
  AgentRunStats,
  AgentRunSummary,
  AgentRunTaskData,
} from "./types/agent-runs";

type MockAgentRunRecord = {
  personas: AgentRunPersonas;
  stats: AgentRunStats;
  summary: AgentRunSummary;
  tasks: {
    tasks: AgentRunTaskData[];
    total: number;
    page: number;
    limit: number;
  };
};

export const mockAgentRunRecords: Record<string, MockAgentRunRecord> = {
  "b3n8-2p5q": {
    personas: {
      round: {
        id: 27,
        name: "Round 27",
        status: "completed",
        startTime: "2024-02-19T13:45:00Z",
        endTime: "2024-02-19T15:35:00Z",
      },
      validator: {
        id: "tao5",
        name: "Tao5 Validator",
        image: "/validators/tao5.png",
        description: "Top validator for long-horizon browsing tasks.",
        website: "https://tao5.autoppia.com",
        github: "https://github.com/autoppia",
      },
      agent: {
        id: "agent-178",
        name: "Aurora Web Agent",
        type: "autonomous",
        image: "/images/autoppia-logo.png",
        description: "Hybrid reasoning agent tuned for synthetic web operations.",
      },
    },
    stats: {
      runId: "b3n8-2p5q",
      overallScore: 92,
      totalTasks: 128,
      successfulTasks: 96,
      failedTasks: 32,
      websites: 4,
      averageTaskDuration: 43.5,
      successRate: 75,
      scoreDistribution: {
        excellent: 44,
        good: 36,
        average: 28,
        poor: 20,
      },
      performanceByWebsite: [
        {
          website: "Autozone",
          tasks: 38,
          successful: 30,
          failed: 8,
          averageScore: 0.93,
          averageDuration: 39.4,
        },
        {
          website: "AutoDining",
          tasks: 32,
          successful: 23,
          failed: 9,
          averageScore: 0.87,
          averageDuration: 45.1,
        },
        {
          website: "AutoCRM",
          tasks: 30,
          successful: 24,
          failed: 6,
          averageScore: 0.9,
          averageDuration: 42.7,
        },
        {
          website: "AutoLodge",
          tasks: 28,
          successful: 19,
          failed: 9,
          averageScore: 0.82,
          averageDuration: 47.9,
        },
      ],
      performanceByUseCase: [
        {
          useCase: "buy_product",
          tasks: 26,
          successful: 22,
          failed: 4,
          averageScore: 0.91,
          averageDuration: 38.8,
        },
        {
          useCase: "book_reservation",
          tasks: 20,
          successful: 14,
          failed: 6,
          averageScore: 0.83,
          averageDuration: 46.3,
        },
        {
          useCase: "create_customer",
          tasks: 18,
          successful: 15,
          failed: 3,
          averageScore: 0.9,
          averageDuration: 41.2,
        },
        {
          useCase: "send_email",
          tasks: 24,
          successful: 18,
          failed: 6,
          averageScore: 0.85,
          averageDuration: 44.6,
        },
        {
          useCase: "booking_flow",
          tasks: 22,
          successful: 15,
          failed: 7,
          averageScore: 0.8,
          averageDuration: 48.1,
        },
      ],
    },
    summary: {
      runId: "b3n8-2p5q",
      agentId: "agent-178",
      roundId: 27,
      validatorId: "tao5",
      startTime: "2024-02-19T13:45:00Z",
      endTime: "2024-02-19T15:35:00Z",
      status: "completed",
      overallScore: 92,
      totalTasks: 128,
      successfulTasks: 96,
      failedTasks: 32,
      duration: 6600,
      ranking: 2,
      topPerformingWebsite: {
        website: "Autozone",
        score: 0.93,
        tasks: 38,
      },
      topPerformingUseCase: {
        useCase: "buy_product",
        score: 0.91,
        tasks: 26,
      },
      recentActivity: [
        {
          timestamp: "2024-02-19T15:35:00Z",
          action: "run_completed",
          details: "Agent run finished with high success rate.",
        },
        {
          timestamp: "2024-02-19T15:10:00Z",
          action: "task_completed",
          details: "Completed use-case booking flow on AutoLodge.",
        },
        {
          timestamp: "2024-02-19T14:20:00Z",
          action: "task_failed",
          details: "Timeout while applying coupon on AutoDining.",
        },
      ],
    },
    tasks: {
      tasks: [
        {
          taskId: "task-9001",
          website: "Autozone",
          useCase: "buy_product",
          prompt: "Purchase a torque wrench priced under $120 and verify delivery options.",
          status: "completed",
          score: 0.95,
          duration: 44,
          startTime: "2024-02-19T13:45:10Z",
          endTime: "2024-02-19T13:45:54Z",
          actions: [
            {
              id: "task-9001-action-1",
              type: "navigate",
              value: "https://autozone.autoppia.com",
              timestamp: "2024-02-19T13:45:10Z",
              duration: 2.1,
              success: true,
            },
            {
              id: "task-9001-action-2",
              type: "other",
              metadata: { query: "torque wrench" },
              timestamp: "2024-02-19T13:45:13Z",
              duration: 6.4,
              success: true,
            },
            {
              id: "task-9001-action-3",
              type: "click",
              selector: "[data-testid='add-to-cart']",
              timestamp: "2024-02-19T13:45:22Z",
              duration: 3.3,
              success: true,
            },
          ],
          screenshots: ["/replays/task-9001.gif"],
        },
        {
          taskId: "task-9002",
          website: "AutoDining",
          useCase: "book_reservation",
          prompt: "Book a table for four at 7:30 PM and confirm email notification.",
          status: "completed",
          score: 0.88,
          duration: 52,
          startTime: "2024-02-19T13:47:10Z",
          endTime: "2024-02-19T13:48:02Z",
          actions: [
            {
              id: "task-9002-action-1",
              type: "navigate",
              value: "https://autodining.autoppia.com",
              timestamp: "2024-02-19T13:47:10Z",
              duration: 2.5,
              success: true,
            },
            {
              id: "task-9002-action-2",
              type: "type",
              selector: "#reservation-time",
              value: "19:30",
              timestamp: "2024-02-19T13:47:24Z",
              duration: 4.9,
              success: true,
            },
            {
              id: "task-9002-action-3",
              type: "click",
              selector: "[data-testid='confirm-reservation']",
              timestamp: "2024-02-19T13:47:39Z",
              duration: 3.8,
              success: true,
            },
          ],
        },
        {
          taskId: "task-9003",
          website: "AutoCRM",
          useCase: "create_customer",
          prompt: "Register a new customer with marketing opt-in enabled.",
          status: "completed",
          score: 0.91,
          duration: 39,
          startTime: "2024-02-19T13:49:15Z",
          endTime: "2024-02-19T13:49:54Z",
          actions: [
            {
              id: "task-9003-action-1",
              type: "navigate",
              value: "https://autocrm.autoppia.com",
              timestamp: "2024-02-19T13:49:15Z",
              duration: 2,
              success: true,
            },
            {
              id: "task-9003-action-2",
              type: "type",
              selector: "#customer-name",
              value: "Jamie Rivera",
              timestamp: "2024-02-19T13:49:19Z",
              duration: 3.7,
              success: true,
            },
            {
              id: "task-9003-action-3",
              type: "click",
              selector: "#marketing-opt-in",
              timestamp: "2024-02-19T13:49:31Z",
              duration: 1.2,
              success: true,
            },
          ],
        },
        {
          taskId: "task-9004",
          website: "AutoLodge",
          useCase: "booking_flow",
          prompt: "Reserve a lake-view room for two nights with late checkout.",
          status: "completed",
          score: 0.82,
          duration: 58,
          startTime: "2024-02-19T13:51:05Z",
          endTime: "2024-02-19T13:52:03Z",
          actions: [
            {
              id: "task-9004-action-1",
              type: "navigate",
              value: "https://autolodge.autoppia.com",
              timestamp: "2024-02-19T13:51:05Z",
              duration: 2.4,
              success: true,
            },
            {
              id: "task-9004-action-2",
              type: "type",
              selector: "#check-in-date",
              value: "2024-03-01",
              timestamp: "2024-02-19T13:51:16Z",
              duration: 4.1,
              success: true,
            },
            {
              id: "task-9004-action-3",
              type: "click",
              selector: "[data-testid='confirm-booking']",
              timestamp: "2024-02-19T13:51:42Z",
              duration: 5.5,
              success: true,
            },
          ],
        },
        {
          taskId: "task-9005",
          website: "AutoDining",
          useCase: "apply_coupon",
          prompt: "Apply the WINTER24 coupon to an existing reservation.",
          status: "failed",
          score: 0.35,
          duration: 63,
          startTime: "2024-02-19T13:53:20Z",
          endTime: "2024-02-19T13:54:23Z",
          error: "Timeout while waiting for coupon validation modal.",
          actions: [
            {
              id: "task-9005-action-1",
              type: "navigate",
              value: "https://autodining.autoppia.com/reservations",
              timestamp: "2024-02-19T13:53:20Z",
              duration: 2.6,
              success: true,
            },
            {
              id: "task-9005-action-2",
              type: "type",
              selector: "#coupon-code",
              value: "WINTER24",
              timestamp: "2024-02-19T13:53:32Z",
              duration: 5.7,
              success: true,
            },
            {
              id: "task-9005-action-3",
              type: "wait",
              metadata: { reason: "Awaiting validation response" },
              timestamp: "2024-02-19T13:53:44Z",
              duration: 20.1,
              success: false,
              error: "Modal did not appear within timeout window.",
            },
          ],
        },
        {
          taskId: "task-9006",
          website: "Autozone",
          useCase: "checkout_flow",
          prompt: "Complete checkout for items in the saved cart with express shipping.",
          status: "completed",
          score: 0.9,
          duration: 55,
          startTime: "2024-02-19T13:55:10Z",
          endTime: "2024-02-19T13:56:05Z",
          actions: [
            {
              id: "task-9006-action-1",
              type: "navigate",
              value: "https://autozone.autoppia.com/cart",
              timestamp: "2024-02-19T13:55:10Z",
              duration: 2.2,
              success: true,
            },
            {
              id: "task-9006-action-2",
              type: "click",
              selector: "[data-testid='select-express-shipping']",
              timestamp: "2024-02-19T13:55:24Z",
              duration: 3.5,
              success: true,
            },
            {
              id: "task-9006-action-3",
              type: "click",
              selector: "[data-testid='submit-order']",
              timestamp: "2024-02-19T13:55:44Z",
              duration: 4.8,
              success: true,
            },
          ],
        },
        {
          taskId: "task-9007",
          website: "AutoCRM",
          useCase: "send_email",
          prompt: "Send follow-up email to new customer with onboarding resources.",
          status: "completed",
          score: 0.86,
          duration: 42,
          startTime: "2024-02-19T13:57:20Z",
          endTime: "2024-02-19T13:58:02Z",
          actions: [
            {
              id: "task-9007-action-1",
              type: "navigate",
              value: "https://autocrm.autoppia.com/customers",
              timestamp: "2024-02-19T13:57:20Z",
              duration: 1.9,
              success: true,
            },
            {
              id: "task-9007-action-2",
              type: "click",
              selector: "[data-testid='send-email']",
              timestamp: "2024-02-19T13:57:33Z",
              duration: 3.1,
              success: true,
            },
            {
              id: "task-9007-action-3",
              type: "type",
              selector: "#email-template",
              value: "onboarding-pack",
              timestamp: "2024-02-19T13:57:40Z",
              duration: 5.6,
              success: true,
            },
          ],
        },
        {
          taskId: "task-9008",
          website: "AutoLodge",
          useCase: "booking_flow",
          prompt: "Adjust existing reservation to include airport shuttle service.",
          status: "failed",
          score: 0.42,
          duration: 61,
          startTime: "2024-02-19T13:59:10Z",
          endTime: "2024-02-19T14:00:11Z",
          error: "Shuttle option toggle not found in DOM.",
          actions: [
            {
              id: "task-9008-action-1",
              type: "navigate",
              value: "https://autolodge.autoppia.com/reservations",
              timestamp: "2024-02-19T13:59:10Z",
              duration: 2.3,
              success: true,
            },
            {
              id: "task-9008-action-2",
              type: "scroll",
              metadata: { distance: 600 },
              timestamp: "2024-02-19T13:59:28Z",
              duration: 6.8,
              success: true,
            },
            {
              id: "task-9008-action-3",
              type: "click",
              selector: "[data-testid='add-shuttle-service']",
              timestamp: "2024-02-19T13:59:40Z",
              duration: 4.6,
              success: false,
              error: "Element selector returned null.",
            },
          ],
        },
      ],
      total: 128,
      page: 1,
      limit: 20,
    },
  },
};
